# Builds the Xamarin.Android application

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@3
  inputs:
    apkFiles: '$(outputDirectory)/*.apk'
    apksign: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'android-apk'
    publishLocation: 'Container'