# Builds the Xamarin.Android application

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/KChristmas-CI-AndroidOnly.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: DownloadSecureFile@1
  name: apkKeystore
  inputs:
    secureFile: android_keystore

- task: AndroidSigning@3
  inputs:
    apkFiles: '$(outputDirectory)/*.apk'
    apksignerKeystoreFile: '$(Agent.TempDirectory)/android_keystore'
    apksignerKeystorePassword: '$(keystore_password)'
    apksignerKeystoreAlias: '2018-and-beyond'
    apksignerKeyPassword: '$(keystore_password)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'android-apk'
    publishLocation: 'Container'