# Builds the Xamarin.Android application

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1
  displayName: "Get latest Nuget tools"

- task: NuGetCommand@2
  displayName: "Run nuget restore"
  inputs:
    restoreSolution: '**/KChristmas-CI-AndroidOnly.sln'

- task: XamarinAndroid@1
  displayName: "Build Xamarin Android project"
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@3
  displayName: "Sign and Zipalign APK"
  inputs:
    apkFiles: '$(outputDirectory)/*.apk'
    apksignerKeystoreFile: 'android_keystore.keystore'
    apksignerKeystorePassword: '$(keystore_password)'
    apksignerKeystoreAlias: '2018-and-beyond'
    apksignerKeyPassword: '$(keystore_password)'


- task: PublishBuildArtifacts@1
  displayName: "Publish output directory"
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'android-apk'
    publishLocation: 'Container'